#!/bin/bash

myenv=`cd $(dirname $BASH_SOURCE[0]) && pwd`
. $myenv/linux/scripts/lib/log.sh

# Ansible creates *.retry files when something goes wrong.
INFO "Removing Ansible *.retry"
find $myenv/ansible/ -type f -name '*.retry' -delete

INFO "Removing Python venv."
rm -rf $myenv/venv
