#!/bin/bash

myconf=`cd $(dirname $BASH_SOURCE[0]) && pwd`
. $myconf/linux/scripts/ensure-ansible.sh

if [ $1 ]
then
  # Called as `config <task>`
  vars="--extra-vars task=$1"
  tasks="apart.yml"
else
  # Called as `config`
  vars=""
  tasks="main.yml"
fi

ansible-playbook --ask-become-pass -i $myconf/ansible/hosts $vars \
  $myconf/ansible/config/$tasks
