#!/bin/bash

. linux/scripts/ensure-ansible.sh

if [ $1 ]
then
  vars="--extra-vars task=$1"
  tasks="apart.yml"
else
  vars=""
  tasks="main.yml"
fi

ansible-playbook --ask-become-pass -i ansible/hosts $vars ansible/config/$tasks
