#!/bin/bash

myenv=$(cd $(dirname $BASH_SOURCE[0]) && pwd)

. $myenv/linux/scripts/install/ansible/ansible.sh

if [ -n "${1:-}" ]
then
  # Called as `config <task>`
  vars="--extra-vars task=$1"
  tasks="apart.yml"
else
  # Called as `config`
  vars=""
  tasks="main.yml"
fi

ansible-playbook --ask-become-pass -i $myenv/ansible/hosts $vars \
  $myenv/ansible/config/$tasks
