#!/bin/bash

myconf=`cd $(dirname $BASH_SOURCE[0]) && pwd`
. $myconf/linux/scripts/install/ansible/ansible.sh

ansible-playbook --ask-become-pass -i $myconf/ansible/hosts \
  $myconf/ansible/install/$1.yml
