#!/bin/bash

myenv=`cd $(dirname $BASH_SOURCE[0]) && pwd`
. $myenv/linux/scripts/install/ansible/ansible.sh

ansible-playbook --ask-become-pass -i $myenv/ansible/hosts \
  $myenv/ansible/install/$1.yml
