- hosts: local

  vars:
    myenv: "{{ playbook_dir | dirname | dirname }}"

  tasks:

  - name: Check awesome exists
    shell:
      cmd: awesome --version
    register: awesome
    failed_when: false
    changed_when: false

  - name: Install awesome
    when: awesome.rc != 0 or awesome.stdout == ''
    include_tasks: packages.yml
    vars:
      packages:
        - xorg
        - awesome

  - name: Link awesome config
    file:
      src: "{{ myenv }}/linux/awesome"
      dest: "~/.config/awesome"
      state: link
      force: true

  - include_tasks: "{{ myenv }}/ansible/config/tasks/xorg.yml"
