---

- hosts: local

  # These high-level vars are available in a nested tasks.
  # WARN: the external `task` var is required!
  vars:
    myenv: "{{ playbook_dir | dirname | dirname }}"

  tasks:

  - name: Settings
    include_vars:
      file: "{{ myenv }}/settings.yml"
      name: settings

  - name: Run task - {{ task }}
    include_tasks: "tasks/{{ task }}.yml"
