- name: Configure Vim desktop entry
  vars:
    vim_desktop: in-vim.desktop
    mimeapps: ~/.config/mimeapps.list
    mimetypes:
      - text/plain
      - text/markdown
      - text/css
      - text/x-scss
      - text/x-python
      - text/x-python3
      - text/x-makefile
      - text/x-chdr
      - text/x-csrc
      - text/x-c++hdr
      - text/x-c++src
      - application/javascript
      - application/json
      - application/x-yaml
      - application/x-shellscript
      - application/x-desktop
  block:
    - name: Add Vim desktop entry
      file:
        src: "{{ myconf }}/linux/lxqt/{{ vim_desktop }}"
        dest: "~/.local/share/applications/{{ vim_desktop }}"
        state: link

    - name: Associate MIME types with Vim desktop entry
      loop: "{{ mimetypes }}"
      ini_file:
        path: "{{ mimeapps }}"
        section: Default Applications
        option: "{{ item }}"
        value: "{{ vim_desktop }};"

    - name: Clear associations that conflicts with Vim
      loop: "{{ mimetypes }}"
      ini_file:
        path: "{{ mimeapps }}"
        section: Added Associations
        option: "{{ item }}"
        state: absent

# TODO: when above get changed
- name: Update desktop database
  shell: update-desktop-database
  become: true
