- name: nvim config
  vars:
    nvim_dir: "{{ settings.user.run }}/nvim"
    runtime_dir: "{{ nvim_dir }}/share/nvim/runtime"
    # See :call stdpath('config')
    config_dir: "~/.config/nvim"
  block:

  - name: Check nvim runtime
    stat:
      path: "{{ runtime_dir }}"
    register: runtime

  # Restore permissions after installing as root
  - name: Reset nvim dir permissions
    when: runtime.stat.exists
    file:
      path: "{{ nvim_dir }}"
      owner: "{{ settings.user.name }}"
      group: "{{ settings.user.name }}"
      recurse: yes
    become: true

  - name: Ensure config files
    when: runtime.stat.exists
    block:

    - name: Ensure {{ config_dir }}
      file:
        path: "{{ config_dir }}"
        state: directory
        recurse: true

    - name: Link configs at {{ config_dir }}
      loop:
        - init.lua
        - plugs.vim
      file:
        src: "{{ myenv }}/nvim/{{ item }}"
        dest: "{{ config_dir }}/{{ item }}"
        state: link
        force: true

  - name: Add reksar's Vim pack
    when: runtime.stat.exists
    file:
      src: "{{ myenv }}/vim/.vim/pack/reksar"
      dest: "{{ runtime_dir }}/pack/reksar"
      state: link
      force: true
