- name: Desktop entry
  vars:
    destination: "~/.local/share/applications"
  block:

  - name: Check destination exists
    stat:
      path: "{{ destination }}"
    register: desktop

  - name: Configure Vim desktop entry
    when: desktop.stat.exists
    vars:
      desktop_entry: in-vim.desktop
      mimeapps: ~/.config/mimeapps.list
      mimetypes:
        - text/plain
        - text/markdown
        - text/css
        - text/x-scss
        - text/x-python
        - text/x-python3
        - text/x-makefile
        - text/x-chdr
        - text/x-csrc
        - text/x-c++hdr
        - text/x-c++src
        - application/javascript
        - application/json
        - application/x-yaml
        - application/x-shellscript
        - application/x-desktop
    block:

    - name: Add {{ desktop_entry }}
      file:
        src: "{{ myenv }}/linux/lxqt/{{ desktop_entry }}"
        dest: "{{ destination }}/{{ desktop_entry }}"
        state: link

    - name: Associate MIME types with {{ desktop_entry }}
      loop: "{{ mimetypes }}"
      ini_file:
        path: "{{ mimeapps }}"
        section: Default Applications
        option: "{{ item }}"
        value: "{{ desktop_entry }};"

    - name: Clear associations that conflicts with {{ desktop_entry }}
      loop: "{{ mimetypes }}"
      ini_file:
        path: "{{ mimeapps }}"
        section: Added Associations
        option: "{{ item }}"
        state: absent

    - name: Update desktop database
      shell: update-desktop-database
      become: true
      register: upd
      changed_when: upd.stdout != ''
