- name: Check X server exists
  shell:
    cmd: xset
  register: xset
  changed_when: false
  failed_when: false

- name: Proceed
  when: xset.rc == 0
  vars:
    config: ~/.xinitrc
  block:

  - name: Ensure the {{ config }}
    lineinfile:
      path: "{{ config }}"
      create: yes
      mode: "755"
      line: "#!/bin/bash"
      insertbefore: BOF

  - name: Add config to {{ config }}
    loop:
      - touchpad
      - brightness
    include_tasks: "{{ myenv }}/ansible/config/tasks/xorg/{{ item }}.yml"

  - name: Set keyboard layout
    lineinfile:
      path: "{{ config }}"
      regex: "setxkbmap .*"
      line: "setxkbmap -layout us,ru -option grp:alt_shift_toggle"

  - name: Apply config
    shell:
      cmd: "{{ config }}"
