- name: Check X server exists
  shell:
    cmd: xset
  changed_when: false

- name: Proceed
  block:

  - name: Install packages
    include_tasks: "{{ myenv }}/ansible/install/packages.yml"
    vars:
      packages:
        - xinput

  - name: Ensure the ~/.xinitrc
    lineinfile:
      path: ~/.xinitrc
      create: yes
      mode: "755"
      line: "#!/bin/bash"
      insertbefore: BOF

  - name: Configure
    loop:
      - touchpad
    include_tasks: "{{ myenv }}/ansible/config/tasks/xorg/{{ item }}.yml"

  - name: Run ~/.xinitrc to apply config
    shell:
      cmd: ~/.xinitrc
