- name: Check xterm exists
  block:

  - name: Check xterm
    shell:
      cmd: uxterm -v
    register: xterm
    failed_when: false
    changed_when: false

  - name: Set whether xterm exists or not
    set_fact:
      xterm_exists: "{{ xterm.rc == 0 and xterm.stdout != '' }}"

- name: Configure xterm
  when: xterm_exists
  block:

  - name: Link ~/.XTerm
    file:
      src: "{{ myenv }}/linux/home/.XTerm"
      dest: "~/.XTerm"
      state: link
      force: true

  - name: Include .XTerm into .Xresources
    lineinfile:
      path: ~/.Xresources
      create: yes
      mode: "644"
      line: "#include \".XTerm\""

  - name: Reload X config
    shell:
      cmd: xrdb -load ~/.Xresources
    register: xrdb
    failed_when: xrdb.rc != 0 or xrdb.stderr != ''
